CREATE TABLE IF NOT EXISTS users (
	id CHAR(36) PRIMARY KEY,
	name VARCHAR(255),
    password VARCHAR(255),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)